// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihnsvmyfuyetvcdufzff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlobnN2bXlmdXlldHZjZHVmemZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyODM0OTcsImV4cCI6MjA1Nzg1OTQ5N30.4nBuwynSGs4zJUz53G5elHWxGLMhnlDf2tm27OoK7WY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);